### ISSUE TITLE
Booglemark menu "Reloading" in 32-bit Safari

### ISSUE THREAD

**Issue by chipfiev** [badjeff/booglemarks#1]
In 64-bit Safari, Booglemarks works as expected.  However, in 32-bit mode, the menu item is there but is empty.  All you get is a grayed-out "Reloading".  I'm using SIMBL 0.9.7a.

BTW - Booglemarks works great.  Thank you for doing something Google won't.

**Comment by badjeff** [comment]
Fixed. Also back-ported to 10.5.
