### ISSUE TITLE
Complete Integration

### ISSUE THREAD

**Issue by joergbattermann** [badjeff/booglemarks#2]
First of all.. awesome work.. nice! However, I'd prefer a 'native' integration in terms of not having a separate menu but (maybe optionally) let booglemarks complete overwrite/sync (back to google, too) my safari bookmarks (including the main bookmarks bar etc).

Is that somewhat 'planned'?

Cheers,
-J

**Comment by badjeff** [comment]
Well.. might 'borrow' some lines from Chrome for Mac later..
