### ISSUE TITLE
Generating Console errors

### ISSUE THREAD

**Issue by mshick** [badjeff/booglemarks#4]
I've noticed that since installing Booglemarks I'm getting a string of errors in Console. Choosing "Reload Bookmarks" triggers them every time. There are about 10 messages like this:

5/14/10 10:01:20 PM com.apple.WebKit.PluginAgent[250]   Fri May 14 22:01:20 mbp-ethernet WebKitPluginHost[1763] <Error>: unknown error code: invalid context

I also get the following errors when visiting a bookmarked site using Booglemarks:

5/14/10 10:06:53 PM WebKitPluginHost[1768]  unknown error code: invalid context
5/14/10 10:06:53 PM WebKitPluginHost[1768]  kCGErrorFailure: Set a breakpoint @ CGErrorBreakpoint() to catch errors as they are logged.
5/14/10 10:06:53 PM com.apple.WebKit.PluginAgent[250]   Fri May 14 22:06:53 mbp-ethernet WebKitPluginHost[1768] <Error>: unknown error code: invalid context
5/14/10 10:06:53 PM com.apple.WebKit.PluginAgent[250]   Fri May 14 22:06:53 mbp-ethernet WebKitPluginHost[1768] <Error>: kCGErrorFailure: Set a breakpoint @ CGErrorBreakpoint() to catch errors as they are logged.

I've also had Booglemarks crash Safari a couple of times on start up.

Still, I'm happy to be able to move back to Google Bookmarks, so thanks for this. I had been using Delicious because there was a Safari plugin available.

**Comment by badjeff** [comment]
OS? SIMBL version? Active SDK in Xcode?

**Comment by mshick** [comment]
Up-to-date 10.6.3, SIMBL 0.9.7a, all programs are current, 64-bit kernel and Safari. Xcode is installed, but has never been run. Computer is MacBook Pro early 2009.

**Comment by mshick** [comment]
I didn't mean to close that—clicked the wrong button.
